apiVersion: v1
kind: ReplicationController
metadata:
  name: node-env-v1
  labels:
    app: node-env
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    app: node-env
    version: v1
  template:
    metadata:
      labels:
        app: node-env
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: node-env
        image: ogazitt/node-env:latest
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080

